# Generated by Django 2.2.4 on 2019-09-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song',
            field=models.FileField(upload_to='media/'),
        ),
    ]
