# Generated by Django 2.2.4 on 2019-09-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20190908_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='tittle',
            field=models.CharField(default='onde usiru', max_length=50),
            preserve_default=False,
        ),
    ]
